language: bash
sudo: required
services:
  - docker
addons:
  apt:
    sources:
    - debian-sid # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck

script:
  - make test
  - docker build .